### ISSUE TITLE
low-beam LiDAR 3D Detection

### ISSUE THREAD

**Issue by century-miao** [Eaphan/GLENet#20]
Hi! I have try this modle to detect low-beam LiDAR datasets (32,16), but it can't detect any target. Do you have any suggestions for adjusting parameters?
Thanks！

**Comment by Eaphan** [comment]
Hi, century-miao. Thanks for your interest in our work. Did you use our released model to detect objects with low-beam LiDAR data? What is the type of dataset you used?
If you used other dataset instead of KITTI and Waymo, I suggest you change its format like KITTI. Or you can train a detector by yourself.

**Comment by century-miao** [comment]
Actually I just simplely replaced the ckpt and config file in demo.py. The data was collected using my own LiDAR (VLP-16)。 I also found that all models on OpenPCDet were unable to detect our data. This seems to be a universal issue, so perhaps I should try training it separately.
Thank you for your work
